version: '3'

services:
  mongo:
    container_name: openhim-mongo
    ports:
      - "27018:27017"
    image: mongo:3.4
    restart: always
    volumes:
     - ./disc/openhim-mongo/data/:/data/
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
      

  core:
    container_name: openhim-core
    image: jembi/openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    
  console:
    container_name: openhim-console
    image: jembi/openhim-console
    ports:
        - "9000:80"
    volumes:
      - ./disc/openhim/config/default.json:/usr/share/nginx/html/config/default.json
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    

  rhies-labware-mediator:
    container_name: rhies-labware-mediator
    image: savicsorg/labtoomrs:latest
    ports:
      - "4000:4000"
    depends_on:
      - core
    volumes:
      - ./disc/labtoomrs/config/:/usr/src/app/savics/labToOmrsMediator/config/
      - ./disc/labtoomrs/logs/:/usr/src/app/savics/logs/
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
  


  rhies-nida-mediator:
    container_name: rhies-nida-mediator
    image: savicsorg/omrstonida:latest
    ports:
      - "4001:4001"
    depends_on:
      - core
    extra_hosts:
      - "onlineauthentication.nida.gov.rw:192.168.100.150"
    volumes:
      - ./disc/omrstonida/config/:/usr/src/app/savics/omrsToNidaMediator/config/
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    


  rhies-dhis2-mediator:
    container_name: rhies-dhis2-mediator
    image: savicsorg/omrstodhis2:latest
    ports:
      - "4002:4002"
    depends_on:
      - core
    volumes:
      - ./disc/omrstodhis2/config/:/usr/src/app/savics/omrsToDHIS2Mediator/config/
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    


  rhies-client-registry-mediator:
    container_name: rhies-client-registry-mediator
    image: savicsorg/omrstocr:latest
    ports:
      - "4004:4004"
    depends_on:
      - core
    volumes:
      - ./disc/omrsToCRMediator/config/:/usr/src/app/savics/omrsToCRMediator/config/
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M


  rhies-facility-registry-mediator:
    container_name: rhies-facility-registry-mediator
    image: savicsorg/frtoomrs:latest
    ports:
      - "4005:4004"
    depends_on:
      - core
    volumes:
      - ./disc/facilityRegistryMediator/config/:/usr/src/app/savics/facilityRegistryMediator/config/
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M



